// Generated by CoffeeScript 1.7.1
(function() {
  var GuineaPageObject;

  module.exports = GuineaPageObject = (function() {
    function GuineaPageObject(driverWrapper) {
      this.driverWrapper = driverWrapper;
    }

    GuineaPageObject.prototype.title = function(done) {
      return this.driverWrapper.getPageTitle(done);
    };

    GuineaPageObject.prototype.submitForm = function(done) {
      return this.driverWrapper.clickElementById('submit', done);
    };

    GuineaPageObject.prototype.clickLink = function(done) {
      return this.driverWrapper.clickElementById('i am a link', done);
    };

    return GuineaPageObject;

  })();

}).call(this);
