// Generated by CoffeeScript 1.7.1
(function() {
  var Logger, logLevelShims;

  Logger = (function() {
    function Logger() {}

    Logger.prototype.debug = typeof console !== "undefined" && console !== null ? console.log : void 0;

    Logger.prototype.test = typeof console !== "undefined" && console !== null ? console.log : void 0;

    Logger.prototype.log = typeof console !== "undefined" && console !== null ? console.log : void 0;

    Logger.prototype.error = typeof console !== "undefined" && console !== null ? console.error : void 0;

    Logger.prototype.warn = typeof console !== "undefined" && console !== null ? console.warn : void 0;

    return Logger;

  })();

  exports.logger = new Logger;

  logLevelShims = function(logger) {
    var levels, lvl, _i, _len;
    levels = ['debug', 'test', 'log', 'error', 'warn'];
    for (_i = 0, _len = levels.length; _i < _len; _i++) {
      lvl = levels[_i];
      switch (lvl) {
        case 'error':
          if (logger[lvl] == null) {
            logger[lvl] = typeof console !== "undefined" && console !== null ? console.error : void 0;
          }
          break;
        case 'warn':
          if (logger[lvl] == null) {
            logger[lvl] = typeof console !== "undefined" && console !== null ? console.warn : void 0;
          }
          break;
        default:
          if (logger[lvl] == null) {
            logger[lvl] = typeof console !== "undefined" && console !== null ? console.log : void 0;
          }
      }
    }
    return logger;
  };

  exports._shimLevels = logLevelShims;

}).call(this);
