// Generated by CoffeeScript 1.7.1
(function() {
  var Jeeves, browser, destinationUrl, should;

  Jeeves = require('../lib/jeeves');

  should = require('should');

  browser = new Jeeves({
    wdLogging: true,
    wdCapabilities: {
      browserName: 'chrome'
    },
    logger: console
  });

  destinationUrl = 'http://admc.io/wd/test-pages/guinea-pig.html';

  browser.init(function() {
    return browser.loadPageAndWait(destinationUrl, function(err, loadedUrl) {
      loadedUrl.should.equal(destinationUrl);
      return browser.getPageTitle(function(err, title) {
        title.should.containEql('WD');
        return browser.clickElementById('i am a link', function(err) {
          return browser.waitForUrlToChange(/guinea-pig2/i, true, function(err, newUrl) {
            newUrl.should.not.equal(destinationUrl);
            return browser.quit(function(err) {
              return console.log('Webdriving has completed');
            });
          });
        });
      });
    });
  });

}).call(this);
