// Generated by CoffeeScript 1.7.1
(function() {
  var Jeeves, accessKey, browser, destinationUrl, should, username;

  Jeeves = require('../lib/jeeves');

  should = require('should');

  username = process.env.SAUCE_USERNAME || "SAUCE_USERNAME";

  accessKey = process.env.SAUCE_ACCESS_KEY || "SAUCE_ACCESS_KEY";

  browser = new Jeeves({
    wdLogging: true,
    wdConfig: {
      host: 'ondemand.saucelabs.com',
      port: 80,
      username: username,
      accessKey: accessKey
    },
    wdCapabilities: {
      browserName: 'chrome',
      platform: 'LINUX',
      tags: ['examples'],
      name: 'This is an example test'
    },
    logger: console
  });

  destinationUrl = 'http://admc.io/wd/test-pages/guinea-pig.html';

  browser.namedSteps({
    startWebDriver: function(next) {
      return browser.init(next);
    },
    loadPage: function(next) {
      return browser.loadPageAndWait(destinationUrl, function(err, loadedUrl) {
        loadedUrl.should.equal(destinationUrl);
        return next(err);
      });
    },
    checkTitle: function(next) {
      return browser.getPageTitle(function(err, title) {
        title.should.containEql('WD');
        return next(err);
      });
    },
    clickLink: function(next) {
      return browser.clickElementById('i am a link', next);
    },
    waitForUrl: function(next) {
      return browser.waitForUrlToChange(/guinea-pig2/i, true, function(err, newUrl) {
        newUrl.should.not.equal(destinationUrl);
        return next(err);
      });
    },
    quit: function(next) {
      return browser.quit(function(err) {
        console.log('Webdriving has completed');
        return next(err);
      });
    }
  });

}).call(this);
